name: Pull file from Google Drive
on: [workflow_dispatch]
jobs:
  main:
    name: Do the Things
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Deps
        run: python3 -m pip install gdown
      - name: Collect File
        run: gdown ${{ secrets.GDRIVE_FILE }}
      - name: Check for Success
        run: ls -l

